name: Minimal Python CI with Embedded Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Upgrade pip and install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Create test file
      run: |
        echo "def test_example():" > test_minimal.py
        echo "    assert 1 + 1 == 2" >> test_minimal.py

    - name: Run pytest on created test file
      run: pytest test_minimal.py

